sudo: false
dist: trusty
language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install -r requirements-test.txt
  - pip install codecov
  - python -m spylon_kernel install --user

script:
  - python run_tests.py -vxrs --capture=sys --color=yes
  # Ensure installability
  - python setup.py sdist
  - pip install --no-use-wheel dist/*.tar.gz

# Cache these at the end of the build
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/spark

after_success:
    - codecov
